// Centralised logo – Handicap Pro brand asset (transparent PNG, 540x540)
// Generated from: Red-Black-Typography-Nine-Brand-Logo-1.jpg
// To update: replace the base64 string below with the new asset's data URI

export const LOGO_DATA_URI =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0CAYAAADL1t+KAABiJklEqVR4nO3deXxU5f3/8ec5M5M9k0lmNqSQkJAtC7IioKALiGUXxQVFcMUr1LXg1+Veq66iVqtrtYJaRFBEpC4gCuIqW0A2QhZCSJYZssm8ybzvH5N5JpPJnJkzM5P5fDzP4+E8M3Nyzjnf8z3P+5wz55w5Q0RERERERERERET0M3L5nQAiIiIiIiIiIiKiW6MDFhEREREREREREdGdYQMWERERERERERER0Z1hAxYRERERERERERHRnWEDFhEREREREREREdGdYQMWERERERERERER0Z1hAxYRERERERERERHRnWEDFhEREREREREREdGd8f8A7dNwXz4u5T0AAAAASUVORK5CYII='
